### ISSUE TITLE
Process safety for coroutine

### ISSUE THREAD

**Issue by Retardium** [ya0211/MRepo#10]
The app crashes always when I click on the Repository button (Manage Magisk modules repository) in settings menu. 

OS: LOS 20 - Android 13
Magisk: 25.2
Device: Oneplus 7 - arm64-v8a
App version: 1.1.1

Crash log:
`java.lang.IllegalArgumentException: Key "1677271481176" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at com.sanmer.mrepo.dy0$b.n0(Unknown Source:167)
	at com.sanmer.mrepo.bz0.p0(Unknown Source:35)
	at com.sanmer.mrepo.h11.a(Unknown Source:10)
	at com.sanmer.mrepo.o01.d0(Unknown Source:688)
	at com.sanmer.mrepo.xy0.d0(Unknown Source:25)
	at com.sanmer.mrepo.ey0.b(Unknown Source:56)
	at com.sanmer.mrepo.vp0.g(Unknown Source:36)
	at com.sanmer.mrepo.p5$b.a0(Unknown Source:18)
	at com.sanmer.mrepo.sx0.h(Unknown Source:12)
	at com.sanmer.mrepo.ux0.g(Unknown Source:10)
	at com.sanmer.mrepo.p5$a.a0(Unknown Source:18)
	at com.sanmer.mrepo.sx0.h(Unknown Source:12)
	at com.sanmer.mrepo.ux0.g(Unknown Source:10)
	at com.sanmer.mrepo.bb2.h(Unknown Source:5)
	at com.sanmer.mrepo.ux0.g(Unknown Source:10)
	at com.sanmer.mrepo.gb0.h(Unknown Source:97)
	at com.sanmer.mrepo.yc.h(Unknown Source:14)
	at com.sanmer.mrepo.ux0.g(Unknown Source:10)
	at com.sanmer.mrepo.cy0.G(Unknown Source:8)
	at com.sanmer.mrepo.yc2$a.a(Unknown Source:63)
	at com.sanmer.mrepo.vd2$c.G(Unknown Source:6)
	at com.sanmer.mrepo.l4.z(Unknown Source:42)
	at com.sanmer.mrepo.vd2.c(Unknown Source:115)
	at com.sanmer.mrepo.dm1.a(Unknown Source:12)
	at com.sanmer.mrepo.by0$b.Z0(Unknown Source:140)
	at com.sanmer.mrepo.by0$b.g(Unknown Source:127)
	at com.sanmer.mrepo.bg.b(Unknown Source:86)
	at com.sanmer.mrepo.vp0.g(Unknown Source:36)
	at com.sanmer.mrepo.mm1.h(Unknown Source:108)
	at com.sanmer.mrepo.yc.h(Unknown Source:14)
	at com.sanmer.mrepo.ux0.g(Unknown Source:10)
	at com.sanmer.mrepo.cy0.G(Unknown Source:8)
	at com.sanmer.mrepo.yc2$a.a(Unknown Source:63)
	at com.sanmer.mrepo.vd2$c.G(Unknown Source:6)
	at com.sanmer.mrepo.l4.z(Unknown Source:42)
	at com.sanmer.mrepo.vd2.c(Unknown Source:115)
	at com.sanmer.mrepo.dm1.a(Unknown Source:12)
	at com.sanmer.mrepo.by0$b.Z0(Unknown Source:140)
	at com.sanmer.mrepo.by0$b.g(Unknown Source:127)
	at com.sanmer.mrepo.i42.h0(Unknown Source:823)
	at com.sanmer.mrepo.x81$a.d(Unknown Source:37)
	at com.sanmer.mrepo.ey0$a.d(Unknown Source:8)
	at com.sanmer.mrepo.by0$b$a.G(Unknown Source:97)
	at com.sanmer.mrepo.yc2$a.a(Unknown Source:63)
	at com.sanmer.mrepo.vd2$c.G(Unknown Source:6)
	at com.sanmer.mrepo.l4.z(Unknown Source:42)
	at com.sanmer.mrepo.vd2.c(Unknown Source:115)
	at com.sanmer.mrepo.dm1.a(Unknown Source:12)
	at com.sanmer.mrepo.by0$b.A(Unknown Source:113)
	at com.sanmer.mrepo.vp0.S0(Unknown Source:126)
	at com.sanmer.mrepo.tq1$a.e(Unknown Source:32)
	at com.sanmer.mrepo.by0$b$b.G(Unknown Source:19)
	at com.sanmer.mrepo.yc2$a.a(Unknown Source:63)
	at com.sanmer.mrepo.vd2$c.G(Unknown Source:6)
	at com.sanmer.mrepo.l4.z(Unknown Source:42)
	at com.sanmer.mrepo.vd2.c(Unknown Source:115)
	at com.sanmer.mrepo.dm1.a(Unknown Source:12)
	at com.sanmer.mrepo.by0$b.Y0(Unknown Source:60)
	at com.sanmer.mrepo.by0$b.S0(Unknown Source:45)
	at com.sanmer.mrepo.tq1$a.e(Unknown Source:32)
	at com.sanmer.mrepo.ag.b(Unknown Source:45)
	at com.sanmer.mrepo.bg$b.h0(Unknown Source:24)
	at com.sanmer.mrepo.x81$a.d(Unknown Source:37)
	at com.sanmer.mrepo.by0$b$a.G(Unknown Source:97)
	at com.sanmer.mrepo.yc2$a.a(Unknown Source:63)
	at com.sanmer.mrepo.vd2$c.G(Unknown Source:6)
	at com.sanmer.mrepo.l4.z(Unknown Source:42)
	at com.sanmer.mrepo.vd2.c(Unknown Source:115)
	at com.sanmer.mrepo.dm1.a(Unknown Source:12)
	at com.sanmer.mrepo.by0$b.A(Unknown Source:113)
	at com.sanmer.mrepo.vp0.S0(Unknown Source:126)
	at com.sanmer.mrepo.tq1$a.h(Unknown Source:52)
	at com.sanmer.mrepo.bb2$a.h0(Unknown Source:17)
	at com.sanmer.mrepo.x81$a.d(Unknown Source:37)
	at com.sanmer.mrepo.ux0.S0(Unknown Source:44)
	at com.sanmer.mrepo.tq1$a.e(Unknown Source:32)
	at com.sanmer.mrepo.by0$b$b.G(Unknown Source:19)
	at com.sanmer.mrepo.yc2$a.a(Unknown Source:63)
	at com.sanmer.mrepo.vd2$c.G(Unknown Source:6)
	at com.sanmer.mrepo.l4.z(Unknown Source:42)
	at com.sanmer.mrepo.vd2.c(Unknown Source:115)
	at com.sanmer.mrepo.dm1.a(Unknown Source:12)
	at com.sanmer.mrepo.by0$b.Y0(Unknown Source:60)
	at com.sanmer.mrepo.by0$b.S0(Unknown Source:45)
	at com.sanmer.mrepo.tq1$a.c(Unknown Source:36)
	at com.sanmer.mrepo.a8$a.h0(Unknown Source:24)
	at com.sanmer.mrepo.x81$a.d(Unknown Source:37)
	at com.sanmer.mrepo.by0$b$a.G(Unknown Source:97)
	at com.sanmer.mrepo.yc2$a.a(Unknown Source:63)
	at com.sanmer.mrepo.vd2$c.G(Unknown Source:6)
	at com.sanmer.mrepo.l4.z(Unknown Source:42)
	at com.sanmer.mrepo.vd2.c(Unknown Source:115)
	at com.sanmer.mrepo.dm1.a(Unknown Source:12)
	at com.sanmer.mrepo.by0$b.A(Unknown Source:113)
	at com.sanmer.mrepo.vp0.S0(Unknown Source:126)
	at com.sanmer.mrepo.tq1$a.h(Unknown Source:52)
	at com.sanmer.mrepo.me$a.h0(Unknown Source:17)
	at com.sanmer.mrepo.x81$a.d(Unknown Source:37)
	at com.sanmer.mrepo.ux0.S0(Unknown Source:44)
	at com.sanmer.mrepo.tq1$a.i(Unknown Source:36)
	at com.sanmer.mrepo.tq1$a.j(Unknown Source:8)
	at com.sanmer.mrepo.wb2$a.h0(Unknown Source:34)
	at com.sanmer.mrepo.x81$a.d(Unknown Source:37)
	at com.sanmer.mrepo.ux0.S0(Unknown Source:44)
	at com.sanmer.mrepo.tq1$a.c(Unknown Source:36)
	at com.sanmer.mrepo.r7.h0(Unknown Source:24)
	at com.sanmer.mrepo.x81$a.d(Unknown Source:37)
	at com.sanmer.mrepo.ux0.S0(Unknown Source:44)
	at com.sanmer.mrepo.tq1$a.e(Unknown Source:32)
	at com.sanmer.mrepo.by0$b$b.G(Unknown Source:19)
	at com.sanmer.mrepo.yc2$a.a(Unknown Source:63)
	at com.sanmer.mrepo.vd2$c.G(Unknown Source:6)
	at com.sanmer.mrepo.l4.z(Unknown Source:42)
	at com.sanmer.mrepo.vd2.c(Unknown Source:115)
	at com.sanmer.mrepo.dm1.a(Unknown Source:12)
	at com.sanmer.mrepo.by0$b.Y0(Unknown Source:60)
	at com.sanmer.mrepo.by0$b.S0(Unknown Source:45)
	at com.sanmer.mrepo.tq1$a.c(Unknown Source:36)
	at com.sanmer.mrepo.y7$a.h0(Unknown Source:55)
	at com.sanmer.mrepo.x81$a.d(Unknown Source:37)
	at com.sanmer.mrepo.by0$b$a.G(Unknown Source:97)
	at com.sanmer.mrepo.yc2$a.a(Unknown Source:63)
	at com.sanmer.mrepo.vd2$c.G(Unknown Source:6)
	at com.sanmer.mrepo.l4.z(Unknown Source:42)
	at com.sanmer.mrepo.vd2.c(Unknown Source:115)
	at com.sanmer.mrepo.dm1.a(Unknown Source:12)
	at com.sanmer.mrepo.by0$b.A(Unknown Source:113)
	at com.sanmer.mrepo.vp0.S0(Unknown Source:126)
	at com.sanmer.mrepo.tq1$a.e(Unknown Source:32)
	at com.sanmer.mrepo.z7$b$a.h0(Unknown Source:12)
	at com.sanmer.mrepo.x81$a.d(Unknown Source:37)
	at com.sanmer.mrepo.ux0.S0(Unknown Source:44)
	at com.sanmer.mrepo.tq1$a.h(Unknown Source:52)
	at com.sanmer.mrepo.bb2$a.h0(Unknown Source:17)
	at com.sanmer.mrepo.x81$a.d(Unknown Source:37)
	at com.sanmer.mrepo.ux0.S0(Unknown Source:44)
	at com.sanmer.mrepo.tq1$a.f(Unknown Source:74)
	at com.sanmer.mrepo.jm1$a.h0(Unknown Source:29)
	at com.sanmer.mrepo.x81$a.d(Unknown Source:37)
	at com.sanmer.mrepo.ux0.S0(Unknown Source:44)
	at com.sanmer.mrepo.tq1$a.e(Unknown Source:32)
	at com.sanmer.mrepo.by0$b$b.G(Unknown Source:19)
	at com.sanmer.mrepo.yc2$a.a(Unknown Source:63)
	at com.sanmer.mrepo.vd2$c.G(Unknown Source:6)
	at com.sanmer.mrepo.l4.z(Unknown Source:42)
	at com.sanmer.mrepo.vd2.c(Unknown Source:115)
	at com.sanmer.mrepo.dm1.a(Unknown Source:12)
	at com.sanmer.mrepo.by0$b.Y0(Unknown Source:60)
	at com.sanmer.mrepo.xx0.R(Unknown Source:26)
	at com.sanmer.mrepo.u81.j(Unknown Source:192)
	at com.sanmer.mrepo.u81.f(Unknown Source:62)
	at androidx.compose.ui.platform.AndroidComposeView.b(Unknown Source:13)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(Unknown Source:19)
	at android.view.View.draw(View.java:23204)
	at android.view.View.updateDisplayListIfDirty(View.java:22068)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22024)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22024)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22024)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22024)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4670)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4381)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3600)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9080)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
`

**Comment by Retardium** [comment]
Now it crashes also when I click on a module in the cloud tab. 
Error:
`java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at com.sanmer.mrepo.jy1.e(Unknown Source:215)
	at com.sanmer.mrepo.b20.f(Unknown Source:68)
	at com.sanmer.mrepo.a20.m(Unknown Source:121)
	at com.sanmer.mrepo.hd.l(Unknown Source:8)
	at com.sanmer.mrepo.a30.run(Unknown Source:100)
	at kotlinx.coroutines.scheduling.a$a.run(Unknown Source:78)
	Suppressed: com.sanmer.mrepo.g20: [af2{Cancelling}@8ff3b13, Dispatchers.Default]
`

**Comment by ya0211** [comment]
Known issue, but I'm not sure how to trigger it yet, restarting or clearing cache can fix it.
