### ISSUE TITLE
Add Rootless Mode

### ISSUE THREAD

**Issue by Wjxfi** [ya0211/MRepo#7]
_non-root>modules>cloud>click on any module>self-closure_

_non-root>modules>cloud>settings>self-closure_

_non-root>modules>cloud>wait>exit the application>wait>wait>system notification: application does not respond>revisit the application>does not respond to clicks_

```FATAL EXCEPTION: main
Process: com.sanmer.mrepo, PID: 23258
java.lang.IllegalStateException: You cannot access the NavBackStackEntry's ViewModels after the NavBackStackEntry is destroyed.
	at com.sanmer.mrepo.if1.r(Unknown Source:48)
	at com.sanmer.mrepo.bc.w0(Unknown Source:12)
	at com.sanmer.mrepo.lc1.e(Unknown Source:161)
	at com.sanmer.mrepo.lc1$f.d0(Unknown Source:34)
	at com.sanmer.mrepo.nq.d0(Unknown Source:57)
	at com.sanmer.mrepo.qs.l0(Unknown Source:291)
	at com.sanmer.mrepo.vs.G(Unknown Source:120)
	at com.sanmer.mrepo.l4.z(Unknown Source:42)
	at com.sanmer.mrepo.qs.S(Unknown Source:127)
	at com.sanmer.mrepo.qs.j0(Unknown Source:35)
	at com.sanmer.mrepo.rt.p(Unknown Source:17)
	at com.sanmer.mrepo.yv1.p(Unknown Source:75)
	at com.sanmer.mrepo.ew1$a.h0(Unknown Source:349)
	at com.sanmer.mrepo.w6$c.doFrame(Unknown Source:6)
	at com.sanmer.mrepo.v6$c.doFrame(Unknown Source:47)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1140)
	at android.view.Choreographer.doCallbacks(Choreographer.java:946)
	at android.view.Choreographer.doFrame(Choreographer.java:870)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
	Suppressed: com.sanmer.mrepo.g20: [com.sanmer.mrepo.ep1@edb0a46, com.sanmer.mrepo.jd1@888e407, af2{Cancelling}@c2d6934, v6@79bd35d]

**Comment by ya0211** [comment]
nonroot? what do you mean?

**Comment by ya0211** [comment]
The current version does not support nonroot mode, the next version will add it.
