### ISSUE TITLE
open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by Willie30F** [ya0211/MRepo#90]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of MRepo. / 我正在使用 MRepo 的最新版本。

### Bug description / Bug 描述

Crashes as soon as I press install or download on any module.

### Expected behavior / 预期行为

Install or download the selected module.

### Actual behavior / 实际行为

Crashes with `open failed: EACCES (Permission denied)` in the notification bar.

### Steps to reproduce / 复现步骤

1. Open the app.
2. Select a module
3. Tap install or download
4. Crash

### UI / OS

Android

### Android Version / Android 版本

14

### Additional info / 额外信息

Google Pixel 8 Pro

**Comment by Willie30F** [comment]
![Screenshot_20231012-094523](https://github.com/ya0211/MRepo/assets/21063653/dc9b2d00-f047-442a-8342-a00bbe732764)

**Comment by ya0211** [comment]
What is your download path?

**Comment by Willie30F** [comment]
The default in the downloads folder.
`/mnt/user/0/emulated/0/Download/MRepo`

**Comment by ya0211** [comment]
I have no idea yet 🤔. You can change the download path and try again.

**Comment by Willie30F** [comment]
Changed the download path, but still the same error occurs.
Maybe something changed with Android 14?

**Comment by ya0211** [comment]
Is `/mnt/...` displayed in the download path?

**Comment by Willie30F** [comment]
Yes it is.
![Screenshot_20231012-171415](https://github.com/ya0211/MRepo/assets/21063653/5b49cd22-5ff3-422f-be2f-f50d77bda7f3)

**Comment by yeedatoy** [comment]
Same happens to me on a14 QPR, every release from stable to each new workflow.

**Comment by Willie30F** [comment]
Good this is fixed now. But with the latest CI build which includes this fix, it still doesn't work. If I now click install or download simply nothing happens. Any idea?

**Comment by ya0211** [comment]
@Willie30F Can you provide logs?

**Comment by Willie30F** [comment]
> @Willie30F Can you provide logs?

If you could give me a hint where to find them, of course. 😆

**Comment by ya0211** [comment]
> If you could give me a hint where to find them, of course. 😆

Use [logcat](https://developer.android.com/tools/logcat)

**Comment by Willie30F** [comment]
Well, thanks for helping me finding the logs for mrepo. But it seems like I tried it with the wrong module, this one probably isn't available anymore in the repo, not sure why it's still listed though.
Tried with another module, works fine now 😆

```
2023-10-16 15:27:51.322 24122 24158 com.sanmer.mrepo I WM-WorkerWrapper : Worker result SUCCESS for Work [ id=1f163812-dec4-457e-875c-1471a113c044, tags={ com.sanmer.mrepo.works.RepoWork } ]
2023-10-16 15:27:57.889 24122 24122 com.sanmer.mrepo I ImeTracker : com.sanmer.mrepo:1a8fc098: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
2023-10-16 15:27:52.586 24122 24122 com.sanmer.mrepo D InsetsController : show(ime(), fromIme=false)
2023-10-16 15:28:02.650 24122 24122 com.sanmer.mrepo W WindowOnBackDispatcher : sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@e84bdae
2023-10-16 15:27:52.586 24122 24122 com.sanmer.mrepo I ImeTracker : com.sanmer.mrepo:ef766045: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT_BY_INSETS_API
2023-10-16 15:27:51.331 24122 24170 com.sanmer.mrepo D <MR_REL>ea1(L28) : update online: 156
2023-10-16 15:27:51.397 24122 24170 com.sanmer.mrepo D <MR_REL>da1(L28) : update local: 12
2023-10-16 15:28:05.283 24122 24122 com.sanmer.mrepo I WM-SystemFgDispatcher : Stopping foreground service
2023-10-16 15:27:50.961 24122 24140 com.sanmer.mrepo D TrafficStats : tagSocket(115) with statsTag=0xffffffff, statsUid=-1
2023-10-16 15:28:05.269 24122 24122 com.sanmer.mrepo I WM-SystemFgDispatcher : Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=com.sanmer.mrepo/androidx.work.impl.foreground.SystemForegroundService (has extras) }
2023-10-16 15:27:50.600 24122 24122 com.sanmer.mrepo E om.sanmer.mrepo : Not starting debugger since process cannot load the jdwp agent.
2023-10-16 15:27:50.630 24122 24122 com.sanmer.mrepo V GraphicsEnvironment : Neither updatable production driver nor prerelease driver is supported.
2023-10-16 15:27:57.939 24122 24122 com.sanmer.mrepo W WindowOnBackDispatcher : sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@114105042 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@fcc3b0b
2023-10-16 15:28:05.262 24122 24168 com.sanmer.mrepo E <MR_REL>DownloadWork(L156) : url = https://apt.izzysoft.de/magisk-test/modules/magisk-captive-manager/v2.1.0_210.zip, filename = Magisk_Captive_Manager_(MCM)_v2.1.0_(210).zip
java.lang.RuntimeException: <HTML><HEAD>
 <TITLE>Not here, not there, not anywhere... (404)</TITLE>
 <META content="text/html; charset=utf-8" http-equiv=Content-Type>
 <META NAME="robots" CONTENT="noindex">
 <STYLE TYPE='text/css'>
  body,table,p { font-family:Verdana,Helvetica,Arial,sans-serif; }
  table,th { background-color:#e5e4e2; }
  table.message {
    margin-top:100px;max-width:800px;
    border:2px groove #625d5d;
    border-radius:7px;
    box-shadow:8px 8px 8px #666;
  }
  table.message th { color:#aa0000; }
  td { padding:0.5em; background-color:#ffffff; }
  p { text-align:justify; }
  p.center { text-align:center; }
  .blackbox {
    font-family: monospace;
    font-weight: bold;
    color: #ffffff;
    background-color: #000000;
    border:2px groove #625d5d;
    padding: 0.2em;
  }
 </STYLE>
</HEAD>
<BODY BGCOLOR='#ffff00'>

<TABLE ALIGN='center' CLASS='message'>
  <TR><TH>Sorry, but I simply couldn't find that!</TH></TR>
  <TR><TD>
    <P>
     <A HREF='http://en.wikipedia.org/wiki/I_Still_Haven%27t_Found_What_I%27m_Looking_For'>I
     still haven't found what you're looking for</A>. Either it was never there
     in the first place (maybe a typo on your end? Or did we announce a wrong URL?),
     it's temporarily gone (needs to be fixed first), or will never be here (yeah,
     <A HREF='http://en.wikipedia.org/wiki/I_Want_It_All'>I want it all</A>, too,
     but that rarely works out – we need something left to dream of, finally).
    </P>
    <P>
     So here are my recommendations:
    </P>
    <UL>
      <LI>If you typed in the URL manually, check it for typos</LI>
      <LI>If you've followed a link, do the same and report it if found</LI>
      <LI><A HREF='http://www.google.com/'>Google it</A></LI>
      <LI><A HREF='https://duckduckgo.com/'>Duck it</A></LI>
      <LI>Take a nap, and try again later. Fresh eyes can see better.</LI>
    </UL>
  </TD></TR>
</TABLE>

</BODY></HTML>

	at com.sanmer.mrepo.au0.t(Unknown Source:141)
	at com.sanmer.mrepo.au0.n(Unknown Source:12)
	at com.sanmer.mrepo.ya3.W0(Unknown Source:4)
	at com.sanmer.mrepo.kr.U(Unknown Source:74)
	at com.sanmer.mrepo.am.o(Unknown Source:60)
	at com.sanmer.mrepo.ea0.t(Unknown Source:100)
	at com.sanmer.mrepo.th.l(Unknown Source:8)
	at com.sanmer.mrepo.f90.run(Unknown Source:109)
	at com.sanmer.mrepo.a3.run(Unknown Source:14)
	at com.sanmer.mrepo.h33.run(Unknown Source:2)
	at com.sanmer.mrepo.w30.run(Unknown Source:93)
2023-10-16 15:27:59.951 24122 24122 com.sanmer.mrepo I WM-SystemFgDispatcher : Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=com.sanmer.mrepo/androidx.work.impl.foreground.SystemForegroundService (has extras) }
2023-10-16 15:28:00.711 24122 24132 com.sanmer.mrepo W System : A resource failed to call release.
2023-10-16 15:27:51.106 24122 24170 com.sanmer.mrepo D <MR_REL>ea1(L28) : update online: 156
2023-10-16 15:27:50.807 24122 24122 com.sanmer.mrepo D <MR_REL>py2(L9) : SuProviderImpl init
2023-10-16 15:27:50.656 24122 24158 com.sanmer.mrepo D CompatibilityChangeReporter : Compat change id reported: 194532703; UID 10315; state: ENABLED
2023-10-16 15:27:50.760 24122 24122 com.sanmer.mrepo D CompatibilityChangeReporter : Compat change id reported: 171228096; UID 10315; state: ENABLED
2023-10-16 15:27:50.656 24122 24158 com.sanmer.mrepo D CompatibilityChangeReporter : Compat change id reported: 253665015; UID 10315; state: ENABLED
2023-10-16 15:27:50.650 24122 24141 com.sanmer.mrepo D <MR_REL>da1(L28) : update local: 12
2023-10-16 15:27:52.524 24122 24122 com.sanmer.mrepo D CompatibilityChangeReporter : Compat change id reported: 289878283; UID 10315; state: ENABLED
2023-10-16 15:27:59.931 24122 24176 com.sanmer.mrepo I WM-Processor : Moving WorkSpec (436f0be6-7699-4779-8539-5d7e3e77bc5e) to the foreground
2023-10-16 15:27:51.197 24122 24164 com.sanmer.mrepo I <MR_REL>ry2(L229) : getLocal: /data/adb/modules
2023-10-16 15:28:04.482 24122 24142 com.sanmer.mrepo D TrafficStats : tagSocket(136) with statsTag=0xffffffff, statsUid=-1
2023-10-16 15:27:50.629 24122 24122 com.sanmer.mrepo V GraphicsEnvironment : angle_gl_driver_selection_values=[]
2023-10-16 15:27:51.373 24122 24170 com.sanmer.mrepo D <MR_REL>ea1(L28) : update online: 156
2023-10-16 15:28:05.265 24122 24145 com.sanmer.mrepo I WM-WorkerWrapper : Worker result FAILURE for Work [ id=90f2b338-6984-40ec-a6f1-4d1b04590372, tags={ com.sanmer.mrepo.works.DownloadWork } ]
2023-10-16 15:28:04.454 24122 24122 com.sanmer.mrepo W WindowOnBackDispatcher : sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@97aeb2
2023-10-16 15:27:50.598 24122 24122 com.sanmer.mrepo I om.sanmer.mrepo : Using CollectorTypeCC GC.
2023-10-16 15:27:50.630 24122 24122 com.sanmer.mrepo V GraphicsEnvironment : com.sanmer.mrepo is not listed in per-application setting
2023-10-16 15:27:59.953 24122 24175 com.sanmer.mrepo I WM-WorkerWrapper : Worker result FAILURE for Work [ id=436f0be6-7699-4779-8539-5d7e3e77bc5e, tags={ com.sanmer.mrepo.works.DownloadWork } ]
2023-10-16 15:27:59.971 24122 24122 com.sanmer.mrepo I WM-SystemFgDispatcher : Stopping foreground service
2023-10-16 15:27:51.115 24122 24122 com.sanmer.mrepo D <MR_REL>am(L96) : initMagisk
2023-10-16 15:28:08.338 24122 24132 com.sanmer.mrepo W System : A resource failed to call close.
2023-10-16 15:27:51.142 24122 24122 com.sanmer.mrepo I <MR_REL>j11(L314) : SuProvider created
2023-10-16 15:27:51.233 24122 24168 com.sanmer.mrepo D TrafficStats : tagSocket(133) with statsTag=0xffffffff, statsUid=-1
2023-10-16 15:27:50.668 24122 24176 com.sanmer.mrepo D CompatibilityChangeReporter : Compat change id reported: 263076149; UID 10315; state: ENABLED
2023-10-16 15:27:57.480 24122 24122 com.sanmer.mrepo D <MR_REL>ModuleViewModel(L124) : ModuleViewModel init: magisk-captive-manager
2023-10-16 15:27:59.765 24122 24170 com.sanmer.mrepo D TrafficStats : tagSocket(124) with statsTag=0xffffffff, statsUid=-1
2023-10-16 15:27:51.396 24122 24145 com.sanmer.mrepo I WM-WorkerWrapper : Worker result SUCCESS for Work [ id=8325c061-704f-43a5-9adc-6f60cf2a63c4, tags={ com.sanmer.mrepo.works.LocalWork } ]
2023-10-16 15:28:03.636 24122 24122 com.sanmer.mrepo I WM-SystemFgDispatcher : Stopping foreground service
2023-10-16 15:27:51.137 24122 24167 com.sanmer.mrepo D <MR_REL>ea1(L28) : update online: 151
2023-10-16 15:28:03.618 24122 24164 com.sanmer.mrepo E <MR_REL>DownloadWork(L156) : url = https://apt.izzysoft.de/magisk-test/modules/magisk-captive-manager/v2.1.0_210.zip, filename = Magisk_Captive_Manager_(MCM)_v2.1.0_(210).zip
java.lang.RuntimeException: <HTML><HEAD>
 <TITLE>Not here, not there, not anywhere... (404)</TITLE>
 <META content="text/html; charset=utf-8" http-equiv=Content-Type>
 <META NAME="robots" CONTENT="noindex">
 <STYLE TYPE='text/css'>
  body,table,p { font-family:Verdana,Helvetica,Arial,sans-serif; }
  table,th { background-color:#e5e4e2; }
  table.message {
    margin-top:100px;max-width:800px;
    border:2px groove #625d5d;
    border-radius:7px;
    box-shadow:8px 8px 8px #666;
  }
  table.message th { color:#aa0000; }
  td { padding:0.5em; background-color:#ffffff; }
  p { text-align:justify; }
  p.center { text-align:center; }
  .blackbox {
    font-family: monospace;
    font-weight: bold;
    color: #ffffff;
    background-color: #000000;
    border:2px groove #625d5d;
    padding: 0.2em;
  }
 </STYLE>
</HEAD>
<BODY BGCOLOR='#ffff00'>

<TABLE ALIGN='center' CLASS='message'>
  <TR><TH>Sorry, but I simply couldn't find that!</TH></TR>
  <TR><TD>
    <P>
     <A HREF='http://en.wikipedia.org/wiki/I_Still_Haven%27t_Found_What_I%27m_Looking_For'>I
     still haven't found what you're looking for</A>. Either it was never there
     in the first place (maybe a typo on your end? Or did we announce a wrong URL?),
     it's temporarily gone (needs to be fixed first), or will never be here (yeah,
     <A HREF='http://en.wikipedia.org/wiki/I_Want_It_All'>I want it all</A>, too,
     but that rarely works out – we need something left to dream of, finally).
    </P>
    <P>
     So here are my recommendations:
    </P>
    <UL>
      <LI>If you typed in the URL manually, check it for typos</LI>
      <LI>If you've followed a link, do the same and report it if found</LI>
      <LI><A HREF='http://www.google.com/'>Google it</A></LI>
      <LI><A HREF='https://duckduckgo.com/'>Duck it</A></LI>
      <LI>Take a nap, and try again later. Fresh eyes can see better.</LI>
    </UL>
  </TD></TR>
</TABLE>

</BODY></HTML>

	at com.sanmer.mrepo.au0.t(Unknown Source:141)
	at com.sanmer.mrepo.au0.n(Unknown Source:12)
	at com.sanmer.mrepo.ya3.W0(Unknown Source:4)
	at com.sanmer.mrepo.kr.U(Unknown Source:74)
	at com.sanmer.mrepo.am.o(Unknown Source:60)
	at com.sanmer.mrepo.ea0.t(Unknown Source:100)
	at com.sanmer.mrepo.th.l(Unknown Source:8)
	at com.sanmer.mrepo.f90.run(Unknown Source:109)
	at com.sanmer.mrepo.a3.run(Unknown Source:14)
	at com.sanmer.mrepo.h33.run(Unknown Source:2)
	at com.sanmer.mrepo.w30.run(Unknown Source:93)
2023-10-16 15:27:50.629 24122 24122 com.sanmer.mrepo V GraphicsEnvironment : angle_gl_driver_selection_pkgs=[]
2023-10-16 15:27:52.939 24122 24122 com.sanmer.mrepo I ImeTracker : com.sanmer.mrepo:ef766045: onShown
2023-10-16 15:27:56.478 24122 24325 com.sanmer.mrepo D ProfileInstaller : Installing profile for com.sanmer.mrepo
2023-10-16 15:28:03.620 24122 24175 com.sanmer.mrepo I WM-WorkerWrapper : Worker result FAILURE for Work [ id=bb396a91-a3c9-4136-b330-1c3ef352c087, tags={ com.sanmer.mrepo.works.DownloadWork } ]
2023-10-16 15:27:50.648 24122 24145 com.sanmer.mrepo D CompatibilityChangeReporter : Compat change id reported: 160794467; UID 10315; state: ENABLED
2023-10-16 15:27:51.353 24122 24166 com.sanmer.mrepo D <MR_REL>ea1(L28) : update online: 156
2023-10-16 15:27:52.633 24122 24122 com.sanmer.mrepo D InsetsController : show(ime(), fromIme=true)
2023-10-16 15:27:50.618 24122 24122 com.sanmer.mrepo D CompatibilityChangeReporter : Compat change id reported: 242716250; UID 10315; state: ENABLED
2023-10-16 15:28:08.314 24122 24130 com.sanmer.mrepo W om.sanmer.mrepo : Cleared Reference was only reachable from finalizer (only reported once)
2023-10-16 15:27:52.542 24122 24122 com.sanmer.mrepo W WindowOnBackDispatcher : OnBackInvokedCallback is not enabled for the application.
Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
2023-10-16 15:27:52.587 24122 24122 com.sanmer.mrepo D InputMethodManager : showSoftInput() view=androidx.compose.ui.platform.AndroidComposeView{1e26b89 VFED..... .F....I. 0,0-1008,2244 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT_BY_INSETS_API
2023-10-16 15:27:50.626 24122 24122 com.sanmer.mrepo D nativeloader : Configuring clns-6 for other apk /data/app/~~N8yvjuyU0u3Imjl3-2rlWw==/com.sanmer.mrepo-QFMkdejX5nIcJT9ZCZ-cUg==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~N8yvjuyU0u3Imjl3-2rlWw==/com.sanmer.mrepo-QFMkdejX5nIcJT9ZCZ-cUg==/lib/arm64, permitted_path=/data:/mnt/expand:/data/user/0/com.sanmer.mrepo
2023-10-16 15:27:50.661 24122 24122 com.sanmer.mrepo D CompatibilityChangeReporter : Compat change id reported: 237531167; UID 10315; state: DISABLED
2023-10-16 15:27:57.918 24122 24122 com.sanmer.mrepo I ImeTracker : com.sanmer.mrepo:dee9cd29: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
2023-10-16 15:27:50.630 24122 24122 com.sanmer.mrepo V GraphicsEnvironment : ANGLE GameManagerService for com.sanmer.mrepo: false
2023-10-16 15:27:58.207 24122 24122 com.sanmer.mrepo I ImeTracker : com.sanmer.mrepo:7aa7371f: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
2023-10-16 15:27:51.261 24122 24142 com.sanmer.mrepo D <MR_REL>ea1(L28) : update online: 156
2023-10-16 15:28:03.615 24122 24122 com.sanmer.mrepo I WM-SystemFgDispatcher : Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=com.sanmer.mrepo/androidx.work.impl.foreground.SystemForegroundService (has extras) }
2023-10-16 15:27:51.142 24122 24122 com.sanmer.mrepo D <MR_REL>j11(L300) : isZygiskEnabled: true
2023-10-16 15:27:51.293 24122 24142 com.sanmer.mrepo D <MR_REL>ea1(L28) : update online: 108
2023-10-16 15:28:04.459 24122 24146 com.sanmer.mrepo D OpenGLRenderer : endAllActiveAnimators on 0xb400007952f52900 (qc3) with handle 0xb4000079b2fe01b0
2023-10-16 15:27:51.395 24122 24164 com.sanmer.mrepo D <MR_REL>da1(L28) : update local: 0
2023-10-16 15:27:59.704 24122 24122 com.sanmer.mrepo D CompatibilityChangeReporter : Compat change id reported: 247079863; UID 10315; state: ENABLED
2023-10-16 15:27:52.453 24122 24122 com.sanmer.mrepo W Choreographer : Frame time is 0.091163 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2023-10-16 15:28:03.589 24122 24176 com.sanmer.mrepo I WM-Processor : Moving WorkSpec (bb396a91-a3c9-4136-b330-1c3ef352c087) to the foreground
2023-10-16 15:27:57.890 24122 24122 com.sanmer.mrepo I ImeTracker : com.sanmer.mrepo:dee9cd29: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
2023-10-16 15:28:02.655 24122 24146 com.sanmer.mrepo D OpenGLRenderer : endAllActiveAnimators on 0xb400007952f67150 (qc3) with handle 0xb4000079b2fe3240
2023-10-16 15:27:51.067 24122 24168 com.sanmer.mrepo D TrafficStats : tagSocket(145) with statsTag=0xffffffff, statsUid=-1
2023-10-16 15:28:05.239 24122 24158 com.sanmer.mrepo I WM-Processor : Moving WorkSpec (90f2b338-6984-40ec-a6f1-4d1b04590372) to the foreground
2023-10-16 15:27:58.208 24122 24122 com.sanmer.mrepo I ImeTracker : com.sanmer.mrepo:1a8fc098: onHidden
2023-10-16 15:27:50.618 24122 24122 com.sanmer.mrepo D CompatibilityChangeReporter : Compat change id reported: 171979766; UID 10315; state: ENABLED
2023-10-16 15:27:51.196 24122 24164 com.sanmer.mrepo D <MR_REL>LocalWork(L61) : LocalWork: doWork
2023-10-16 15:27:52.565 24122 24122 com.sanmer.mrepo D Compose Focus : Owner FocusChanged(true)
2023-10-16 15:27:50.736 24122 24140 com.sanmer.mrepo D <MR_REL>RepoWork(L57) : RepoWork: doWork
2023-10-16 15:28:00.712 24122 24132 com.sanmer.mrepo W System : A resource failed to call close.
2023-10-16 15:27:51.165 24122 24164 com.sanmer.mrepo D <MR_REL>ea1(L28) : update online: 156
2023-10-16 15:28:02.684 24122 24164 com.sanmer.mrepo D TrafficStats : tagSocket(131) with statsTag=0xffffffff, statsUid=-1
2023-10-16 15:27:57.918 24122 24122 com.sanmer.mrepo W RemoteInputConnectionImpl : requestCursorAnchorInfo on inactive InputConnection
2023-10-16 15:28:08.341 24122 24132 com.sanmer.mrepo W System : A resource failed to call close.
2023-10-16 15:27:50.743 24122 24122 com.sanmer.mrepo D <MR_REL>RepositoryViewModel(L65) : RepositoryViewModel init
2023-10-16 15:27:50.689 24122 24140 com.sanmer.mrepo D <MR_REL>ea1(L28) : update online: 156
2023-10-16 15:27:57.484 24122 24122 com.sanmer.mrepo W WindowOnBackDispatcher : OnBackInvokedCallback is not enabled for the application.
Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
2023-10-16 15:27:50.629 24122 24122 com.sanmer.mrepo V GraphicsEnvironment : Currently set values for:
2023-10-16 15:27:59.951 24122 24170 com.sanmer.mrepo E <MR_REL>DownloadWork(L156) : url = https://apt.izzysoft.de/magisk-test/modules/magisk-captive-manager/v2.1.0_210.zip, filename = Magisk_Captive_Manager_(MCM)_v2.1.0_(210).zip
java.lang.RuntimeException: <HTML><HEAD>
 <TITLE>Not here, not there, not anywhere... (404)</TITLE>
 <META content="text/html; charset=utf-8" http-equiv=Content-Type>
 <META NAME="robots" CONTENT="noindex">
 <STYLE TYPE='text/css'>
  body,table,p { font-family:Verdana,Helvetica,Arial,sans-serif; }
  table,th { background-color:#e5e4e2; }
  table.message {
    margin-top:100px;max-width:800px;
    border:2px groove #625d5d;
    border-radius:7px;
    box-shadow:8px 8px 8px #666;
  }
  table.message th { color:#aa0000; }
  td { padding:0.5em; background-color:#ffffff; }
  p { text-align:justify; }
  p.center { text-align:center; }
  .blackbox {
    font-family: monospace;
    font-weight: bold;
    color: #ffffff;
    background-color: #000000;
    border:2px groove #625d5d;
    padding: 0.2em;
  }
 </STYLE>
</HEAD>
<BODY BGCOLOR='#ffff00'>

<TABLE ALIGN='center' CLASS='message'>
  <TR><TH>Sorry, but I simply couldn't find that!</TH></TR>
  <TR><TD>
    <P>
     <A HREF='http://en.wikipedia.org/wiki/I_Still_Haven%27t_Found_What_I%27m_Looking_For'>I
     still haven't found what you're looking for</A>. Either it was never there
     in the first place (maybe a typo on your end? Or did we announce a wrong URL?),
     it's temporarily gone (needs to be fixed first), or will never be here (yeah,
     <A HREF='http://en.wikipedia.org/wiki/I_Want_It_All'>I want it all</A>, too,
     but that rarely works out – we need something left to dream of, finally).
    </P>
    <P>
     So here are my recommendations:
    </P>
    <UL>
      <LI>If you typed in the URL manually, check it for typos</LI>
      <LI>If you've followed a link, do the same and report it if found</LI>
      <LI><A HREF='http://www.google.com/'>Google it</A></LI>
      <LI><A HREF='https://duckduckgo.com/'>Duck it</A></LI>
      <LI>Take a nap, and try again later. Fresh eyes can see better.</LI>
    </UL>
  </TD></TR>
</TABLE>

</BODY></HTML>

	at com.sanmer.mrepo.au0.t(Unknown Source:141)
	at com.sanmer.mrepo.au0.n(Unknown Source:12)
	at com.sanmer.mrepo.ya3.W0(Unknown Source:4)
	at com.sanmer.mrepo.kr.U(Unknown Source:74)
	at com.sanmer.mrepo.am.o(Unknown Source:60)
	at com.sanmer.mrepo.ea0.t(Unknown Source:100)
	at com.sanmer.mrepo.th.l(Unknown Source:8)
	at com.sanmer.mrepo.f90.run(Unknown Source:109)
	at com.sanmer.mrepo.a3.run(Unknown Source:14)
	at com.sanmer.mrepo.h33.run(Unknown Source:2)
	at com.sanmer.mrepo.w30.run(Unknown Source:93)
```
Maybe an error message would be helpful if something fails like http 404 not found 😜

Thanks for your help 👍🙂

**Comment by ya0211** [comment]
This is a issue of the repository, check whether the link of repository is correct.

**Comment by yeedatoy** [comment]
Yeah you fixed the original issue very quickly. Thank you! Zero problems ever since, except when it's something out of your hands and related to someone's repository
