### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Hesidv** [ya0211/MRepo#95]
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of MRepo. / 我正在使用 MRepo 的最新版本。

### Bug description / Bug 描述

Crashed when download module

### Expected behavior / 预期行为

Download a module

### Actual behavior / 实际行为

FATAL EXCEPTION: main
Process: com.sanmer.mrepo, PID: 11615
android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{7f3c596 11615:com.sanmer.mrepo/u0a170} targetSDK=34 has been prohibited
	at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:53)
	at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
	at android.os.Parcel.readParcelable(Parcel.java:4852)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
	at android.app.Service.startForeground(Service.java:862)
	at com.sanmer.mrepo.y03.a(Unknown Source:0)
	at com.sanmer.mrepo.v03.run(Unknown Source:14)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

### UI / OS

AOSP

### Android Version / Android 版本

14

**Comment by ya0211** [comment]
Already fixed (#93)
